In [32]:
from numpy import linalg as lin
import numpy as np
def acc(*pos):
    lacc=[]
    b=0
    for j in pos:
        b+=1
        a=0
        accx=0
        accy=0
        accz=0
        for i in pos:
            a+=1
            if a!=b:
                accx+=-i[3]*39.748*(j[0]-i[0])/(lin.norm(j[:3]-i[:3]))**(3.0)
                accy+=-i[3]*39.748*(j[1]-i[1])/(lin.norm(j[:3]-i[:3]))**(3.0)
                accz+=-i[3]*39.748*(j[2]-i[2])/(lin.norm(j[:3]-i[:3]))**(3.0)
                
        l=np.array([accx,accy,accz])
        if a!=b:    
            lacc.append(l)
    return lacc

In [33]:
acc(np.array([1,2,3,4]),np.array([1,1,2,2]),np.array([1,1,3,4]),np.array([4,3,9,6]),np.array([1,1,1,1]))

[array([   2.29324808, -189.88883351,  -30.62992257]),
 array([  1.46554869,  57.18919314, 178.87577429]),
 array([  2.08590087, 160.38260058, -85.26119825]),
 array([-3.58443088, -1.8800099 , -7.44935518])]